title: SimpleGAS
description: The Simple Gameplay Ability System plugin documentation.
theme: just-the-docs

url: https://straytrain.github.io/SimpleGAS/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
