title: SimpleGAS
description: The Simple Gameplay Ability System plugin documentation.
theme: just-the-docs
color_scheme: dark

url: https://straytrain.github.io/SimpleGAS/

aux_links:
  SimpleGAS on GitHub:
    - https://github.com/strayTrain/SimpleGameplayAbilitySystem

aux_links_new_tab: true

mermaid:
  version: "11.4.1"

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: yellow
  tip:
    title: Tip
    color: blue
