title: SimpleGAS
description: The Simple Gameplay Ability System plugin documentation.
theme: just-the-docs

url: https://straytrain.github.io/SimpleGAS/

aux_links:
  SimpleGAS on GitHub:
    - https://github.com/strayTrain/SimpleGameplayAbilitySystem

color_scheme: dark

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: yellow
  tip:
    title: Tip
    color: blue
