title: SimpleGAS
description: The Simple Gameplay Ability System plugin documentation.
theme: just-the-docs

url: https://straytrain.github.io/SimpleGAS/

color_scheme: dark

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: yellow
  tip:
    title: Tip
    color: blue
